apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - gateway-api-deployment.yaml
  - gateway-api-service.yaml
  - gateway-api-ingress.yaml
  - gateway-api-certificate.yaml
  - gateway-agent-deployment.yaml
  - gateway-agent-service.yaml
  - collector-deployment.yaml
  - collector-service.yaml
  - ml-trainer-cronjob.yaml
  - ml-inference-deployment.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - dashboard-ingress.yaml
  - dashboard-certificate.yaml

labels:
  - pairs:
      variant: gateway
    includeSelectors: false
