apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - streaming-source.yaml
  - streaming-kustomization.yaml
  - streaming-operator-helmrelease.yaml
  - streaming-platform-helmrelease.yaml
