apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pi-agents
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: pi-agents
spec:
  interval: 1m
  url: https://github.com/KacperJarocki/pi-agents.git
  ref:
    branch: main
