apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pi-agents
  namespace: iot-security
  labels:
    app.kubernetes.io/part-of: pi-agents
spec:
  interval: 5m
  dependsOn:
    - name: strimzi-operator
      namespace: strimzi-system
    - name: barman-cloud
      namespace: cnpg-system
  chart:
    spec:
      chart: ./charts/pi-agents
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: pi-agents
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    streaming:
      enabled: true
    kafka:
      enabled: true
      bootstrapServers: pi-agents-kafka-bootstrap:9092
    externalServices:
      existingSecret: iot-security-external-services
