apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-security

resources:
  - namespace.yaml
  - pvc.yaml
  - network-policy.yaml
  - gateway-api-netpol.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: iot-security
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
